### ISSUE TITLE
fork support

### ISSUE THREAD

**Issue by tsucchi** [tsucchi/p5-Otogiri-Plugin-AutoReconnect#1]
implement fork safe reconnect. (but I don't know what to do...)

**Comment by ytnobody** [comment]
I used it in my webapp http://rainview.ytnobody.net/ and now it works finely.
- Docker Container
- Server::Starter + Starman
- 6 workers

**Comment by tsucchi** [comment]
fixed in https://github.com/tsucchi/p5-Otogiri-Plugin-AutoReconnect/pull/3

**Comment by ytnobody** [comment]
:+1:
